# Some changes made

sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jvives/docker-react -f Dockerfile.dev .

  script: 
    - docker run -e CI=true jvives/docker-react npm run test